import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import DashboardLayout from "@/components/dashboard/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Download, ExternalLink, Loader2 } from "lucide-react";
import { CURRENCIES, formatCurrency, type Currency } from "@/lib/roi/calculator";

type Submission = {
  id: string;
  full_name: string;
  email: string;
  phone: string | null;
  business_name: string | null;
  business_type: string | null;
  preferred_contact_method: string | null;
  currency: string;
  estimated_monthly_opportunity: number;
  estimated_annual_opportunity: number;
  lead_status: string | null;
  contact_id: string | null;
  created_at: string;
};

export default function DashboardRoiSubmissions() {
  const { workspaceId } = useParams<{ workspaceId: string }>();
  const [search, setSearch] = useState("");
  const [currency, setCurrency] = useState<string>("all");
  const [status, setStatus] = useState<string>("all");
  const [type, setType] = useState<string>("all");

  const { data, isLoading } = useQuery({
    queryKey: ["roi-submissions"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("roi_calculator_submissions")
        .select(
          "id, full_name, email, phone, business_name, business_type, preferred_contact_method, currency, estimated_monthly_opportunity, estimated_annual_opportunity, lead_status, contact_id, created_at",
        )
        .order("created_at", { ascending: false })
        .limit(500);
      if (error) throw error;
      return (data ?? []) as Submission[];
    },
  });

  const filtered = useMemo(() => {
    let list = data ?? [];
    if (search) {
      const q = search.toLowerCase();
      list = list.filter(
        (r) =>
          r.full_name.toLowerCase().includes(q) ||
          r.email.toLowerCase().includes(q) ||
          (r.business_name ?? "").toLowerCase().includes(q),
      );
    }
    if (currency !== "all") list = list.filter((r) => r.currency === currency);
    if (status !== "all") list = list.filter((r) => (r.lead_status ?? "new") === status);
    if (type !== "all") list = list.filter((r) => r.business_type === type);
    return list;
  }, [data, search, currency, status, type]);

  const businessTypes = useMemo(
    () => Array.from(new Set((data ?? []).map((r) => r.business_type).filter(Boolean))) as string[],
    [data],
  );

  const exportCsv = () => {
    const headers = [
      "Full name",
      "Email",
      "Phone",
      "Business",
      "Type",
      "Preferred contact",
      "Currency",
      "Monthly opportunity",
      "Annual opportunity",
      "Status",
      "Created",
    ];
    const rows = filtered.map((r) => [
      r.full_name,
      r.email,
      r.phone ?? "",
      r.business_name ?? "",
      r.business_type ?? "",
      r.preferred_contact_method ?? "",
      r.currency,
      r.estimated_monthly_opportunity.toFixed(2),
      r.estimated_annual_opportunity.toFixed(2),
      r.lead_status ?? "new",
      r.created_at,
    ]);
    const csv = [headers, ...rows]
      .map((row) => row.map((v) => `"${String(v).replace(/"/g, '""')}"`).join(","))
      .join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `roi-submissions-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <DashboardLayout>
      <div className="space-y-6 p-6">
        <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end">
          <div>
            <h1 className="text-2xl font-bold text-primary">ROI Calculator Submissions</h1>
            <p className="text-sm text-muted-foreground">
              Leads generated by the public ROI Savings Calculator.
            </p>
          </div>
          <Button variant="outline" onClick={exportCsv} disabled={!filtered.length}>
            <Download className="mr-2 h-4 w-4" /> Export CSV
          </Button>
        </div>

        <Card>
          <CardHeader className="border-b">
            <CardTitle className="text-base">Filters</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-3 pt-6 md:grid-cols-4">
            <Input
              placeholder="Search name, email, business…"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
            <Select value={currency} onValueChange={setCurrency}>
              <SelectTrigger>
                <SelectValue placeholder="Currency" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All currencies</SelectItem>
                {CURRENCIES.map((c) => (
                  <SelectItem key={c.code} value={c.code}>
                    {c.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Select value={status} onValueChange={setStatus}>
              <SelectTrigger>
                <SelectValue placeholder="Status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All statuses</SelectItem>
                <SelectItem value="new">New</SelectItem>
                <SelectItem value="high_intent">High intent</SelectItem>
                <SelectItem value="contacted">Contacted</SelectItem>
                <SelectItem value="won">Won</SelectItem>
                <SelectItem value="lost">Lost</SelectItem>
              </SelectContent>
            </Select>
            <Select value={type} onValueChange={setType}>
              <SelectTrigger>
                <SelectValue placeholder="Business type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All types</SelectItem>
                {businessTypes.map((t) => (
                  <SelectItem key={t} value={t}>
                    {t}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-0">
            {isLoading ? (
              <div className="flex items-center justify-center p-12 text-muted-foreground">
                <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Loading submissions…
              </div>
            ) : filtered.length === 0 ? (
              <p className="p-12 text-center text-sm text-muted-foreground">
                No submissions match your filters yet.
              </p>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead className="border-b bg-muted/40 text-left text-xs uppercase text-muted-foreground">
                    <tr>
                      <th className="px-4 py-3">Name</th>
                      <th className="px-4 py-3">Business</th>
                      <th className="px-4 py-3">Contact</th>
                      <th className="px-4 py-3">Type</th>
                      <th className="px-4 py-3 text-right">Monthly opp</th>
                      <th className="px-4 py-3 text-right">Annual opp</th>
                      <th className="px-4 py-3">Status</th>
                      <th className="px-4 py-3">Submitted</th>
                      <th className="px-4 py-3" />
                    </tr>
                  </thead>
                  <tbody>
                    {filtered.map((r) => (
                      <tr key={r.id} className="border-b transition-colors hover:bg-muted/30">
                        <td className="px-4 py-3 font-medium text-primary">{r.full_name}</td>
                        <td className="px-4 py-3">{r.business_name ?? "—"}</td>
                        <td className="px-4 py-3">
                          <div className="text-xs">{r.email}</div>
                          <div className="text-xs text-muted-foreground">{r.phone ?? "—"}</div>
                        </td>
                        <td className="px-4 py-3 text-xs">{r.business_type ?? "—"}</td>
                        <td className="px-4 py-3 text-right font-semibold text-accent">
                          {formatCurrency(r.estimated_monthly_opportunity, r.currency as Currency)}
                        </td>
                        <td className="px-4 py-3 text-right">
                          {formatCurrency(r.estimated_annual_opportunity, r.currency as Currency)}
                        </td>
                        <td className="px-4 py-3">
                          <Badge
                            variant={r.lead_status === "high_intent" ? "default" : "outline"}
                            className={
                              r.lead_status === "high_intent"
                                ? "bg-accent text-accent-foreground"
                                : ""
                            }
                          >
                            {r.lead_status ?? "new"}
                          </Badge>
                        </td>
                        <td className="px-4 py-3 text-xs text-muted-foreground">
                          {new Date(r.created_at).toLocaleDateString()}
                        </td>
                        <td className="px-4 py-3">
                          {r.contact_id && workspaceId ? (
                            <Button asChild variant="ghost" size="sm">
                              <Link to={`/dashboard/${workspaceId}/leads?leadId=${r.contact_id}`}>
                                <ExternalLink className="h-4 w-4" />
                              </Link>
                            </Button>
                          ) : null}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
}
