// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-leads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/guard.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
var MAX_ROWS = 50;
var RATE_LIMIT_PER_MINUTE = 60;
var DEFAULT_ACCESS = "view";
function userClient(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function adminClient() {
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!key) return null;
  return createClient(process.env.SUPABASE_URL, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function fail(text) {
  return { content: [{ type: "text", text }], isError: true };
}
function ok(text, structured) {
  return { content: [{ type: "text", text }], structuredContent: structured };
}
function clampLimit(limit) {
  if (!limit || !Number.isFinite(limit) || limit < 1) return 25;
  return Math.min(Math.floor(limit), MAX_ROWS);
}
async function audit(params) {
  const admin = adminClient();
  if (!admin) return;
  try {
    await admin.from("mcp_tool_activity").insert({
      workspace_id: params.workspaceId,
      user_id: params.userId,
      oauth_client_id: params.clientId,
      tool_name: params.tool,
      summary: params.summary.slice(0, 500),
      risk_level: params.risk,
      approval_status: "not_required",
      execution_status: params.execution,
      error_code: params.errorCode ?? null,
      duration_ms: params.durationMs ?? null
    });
  } catch {
  }
}
async function withinRateLimit(userId, workspaceId) {
  const admin = adminClient();
  if (!admin) return true;
  const window = new Date(Math.floor(Date.now() / 6e4) * 6e4).toISOString();
  try {
    const { data } = await admin.from("mcp_rate_limits").select("id, request_count").eq("user_id", userId).eq("window_start", window).limit(1).maybeSingle();
    if (!data) {
      await admin.from("mcp_rate_limits").insert({ user_id: userId, workspace_id: workspaceId, window_start: window, request_count: 1 });
      return true;
    }
    if (data.request_count >= RATE_LIMIT_PER_MINUTE) return false;
    await admin.from("mcp_rate_limits").update({ request_count: data.request_count + 1 }).eq("id", data.id);
    return true;
  } catch {
    return true;
  }
}
async function touchConnection(workspaceId, clientId, userId) {
  const admin = adminClient();
  if (!admin || !clientId) return;
  try {
    const { data } = await admin.from("mcp_connections").select("id").eq("workspace_id", workspaceId).eq("oauth_client_id", clientId).maybeSingle();
    if (data) {
      await admin.from("mcp_connections").update({ last_seen_at: (/* @__PURE__ */ new Date()).toISOString(), status: "active" }).eq("id", data.id);
    } else {
      await admin.from("mcp_connections").insert({
        workspace_id: workspaceId,
        client_key: "custom",
        oauth_client_id: clientId,
        status: "active",
        last_seen_at: (/* @__PURE__ */ new Date()).toISOString(),
        created_by: userId
      });
    }
  } catch {
  }
}
async function withGuard(ctx, opts, run) {
  const started = Date.now();
  const risk = opts.risk ?? (opts.write ? "high" : "low");
  const clientId = (() => {
    try {
      return ctx.getClientId?.() ?? null;
    } catch {
      return null;
    }
  })();
  if (!ctx.isAuthenticated()) {
    return fail("Not authenticated. Reconnect your AI assistant to NexusFlo24.");
  }
  const userId = ctx.getUserId();
  const supabase = userClient(ctx);
  const { data: memberships, error: memErr } = await supabase.from("workspace_members").select("workspace_id").eq("user_id", userId);
  if (memErr) {
    await audit({ workspaceId: null, userId, clientId, tool: opts.tool, summary: "membership lookup failed", risk, execution: "failed", errorCode: memErr.code });
    return fail("Could not verify your workspace access.");
  }
  const allowed = (memberships ?? []).map((m) => m.workspace_id);
  let workspaceId = opts.workspaceId ?? allowed[0];
  if (opts.requireWorkspace !== false) {
    if (!workspaceId) {
      await audit({ workspaceId: null, userId, clientId, tool: opts.tool, summary: "no workspace", risk, execution: "rejected" });
      return fail("No NexusFlo24 workspace is available for your account.");
    }
    if (!allowed.includes(workspaceId)) {
      await audit({ workspaceId: null, userId, clientId, tool: opts.tool, summary: "workspace access denied", risk, execution: "rejected", errorCode: "workspace_forbidden" });
      return fail("You do not have access to that workspace.");
    }
  }
  workspaceId = workspaceId ?? "";
  if (!await withinRateLimit(userId, workspaceId || null)) {
    await audit({ workspaceId: workspaceId || null, userId, clientId, tool: opts.tool, summary: "rate limited", risk, execution: "rejected", errorCode: "rate_limited" });
    return fail("Rate limit reached. Please try again in a minute.");
  }
  if (workspaceId) {
    const { data: perm } = await supabase.from("mcp_tool_permissions").select("access_level, require_approval").eq("workspace_id", workspaceId).eq("permission_group", opts.group).maybeSingle();
    const level = perm?.access_level ?? DEFAULT_ACCESS;
    if (level === "none") {
      await audit({ workspaceId, userId, clientId, tool: opts.tool, summary: "permission denied", risk, execution: "rejected", errorCode: "permission_denied" });
      return fail(`AI assistant access to ${opts.group} is turned off for this workspace.`);
    }
    if (opts.write && level === "view") {
      await audit({ workspaceId, userId, clientId, tool: opts.tool, summary: "write not permitted", risk, execution: "rejected", errorCode: "write_denied" });
      return fail(`Your workspace only allows read-only AI access to ${opts.group}.`);
    }
    if (opts.write && (perm?.require_approval ?? true)) {
      await audit({ workspaceId, userId, clientId, tool: opts.tool, summary: "approval required", risk, execution: "rejected", errorCode: "approval_required" });
      return fail("This action requires approval inside NexusFlo24 before an AI assistant can run it.");
    }
    await touchConnection(workspaceId, clientId, userId);
  }
  try {
    const result = await run({ supabase, workspaceId, userId });
    await audit({
      workspaceId: workspaceId || null,
      userId,
      clientId,
      tool: opts.tool,
      summary: result.isError ? "tool returned an error" : "completed",
      risk,
      execution: result.isError ? "failed" : "success",
      durationMs: Date.now() - started
    });
    return result;
  } catch (e) {
    await audit({ workspaceId: workspaceId || null, userId, clientId, tool: opts.tool, summary: "unhandled error", risk, execution: "failed", durationMs: Date.now() - started });
    return fail("That request could not be completed.");
  }
}

// src/lib/mcp/tools/list-leads.ts
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List leads",
  description: "List the most recent NexusFlo24 leads for the signed-in user's workspace (name, email, phone, status, stage, score, source, tags, created_at). Optional workspace_id, status, and search filters. Max 50 rows.",
  inputSchema: {
    workspace_id: z.string().uuid().optional().describe("Optional workspace to scope leads to."),
    status: z.string().optional().describe("Optional status filter (e.g. New, Warm, Hot)."),
    search: z.string().optional().describe("Optional case-insensitive match on name or email."),
    limit: z.number().int().optional().describe("Max rows to return (default 25, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, status, search, limit }, ctx) => withGuard(ctx, { tool: "list_leads", group: "crm", workspaceId: workspace_id }, async ({ supabase, workspaceId }) => {
    let q = supabase.from("leads").select("id, full_name, email, phone, status, pipeline_stage, score, source, tags, created_at").eq("workspace_id", workspaceId).order("created_at", { ascending: false }).limit(clampLimit(limit));
    if (status) q = q.eq("status", status);
    if (search) q = q.or(`full_name.ilike.%${search}%,email.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return ok(JSON.stringify(data ?? []), { leads: data ?? [] });
  })
});

// src/lib/mcp/tools/create-lead.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_lead_default = defineTool2({
  name: "create_lead",
  title: "Create lead",
  description: "Create a new CRM lead in NexusFlo24 for the signed-in user's workspace. Requires at least full_name or email. Optional notes, source, tags, status.",
  inputSchema: {
    workspace_id: z2.string().uuid().describe("Workspace to add the lead to."),
    full_name: z2.string().optional(),
    email: z2.string().email().optional(),
    phone: z2.string().optional(),
    source: z2.string().optional().describe("Where the lead came from (e.g. 'ChatGPT MCP')."),
    status: z2.string().optional(),
    notes: z2.string().optional(),
    tags: z2.array(z2.string()).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    if (!input.full_name && !input.email)
      return {
        content: [{ type: "text", text: "Provide at least full_name or email." }],
        isError: true
      };
    const { data, error } = await client(ctx).from("leads").insert({
      user_id: ctx.getUserId(),
      workspace_id: input.workspace_id,
      full_name: input.full_name ?? null,
      email: input.email ?? null,
      phone: input.phone ?? null,
      source: input.source ?? "MCP",
      status: input.status ?? "New",
      notes: input.notes ?? null,
      tags: input.tags ?? null
    }).select().single();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Lead created: ${data.id}` }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/list-campaigns.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client2(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_campaigns_default = defineTool3({
  name: "list_campaigns",
  title: "List campaigns",
  description: "List the signed-in user's marketing campaigns (Email / WhatsApp / SMS) in NexusFlo24 with status and channel.",
  inputSchema: {
    workspace_id: z3.string().uuid().optional(),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = client2(ctx).from("campaigns").select("id, name, type, status, created_at, updated_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (workspace_id) q = q.eq("workspace_id", workspace_id);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { campaigns: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-workspaces.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_workspaces_default = defineTool4({
  name: "list_workspaces",
  title: "List workspaces",
  description: "List the signed-in user's NexusFlo24 workspaces. Use the returned workspace_id when calling other tools.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => withGuard(
    ctx,
    { tool: "list_workspaces", group: "settings", requireWorkspace: false },
    async () => {
      const supabase = userClient(ctx);
      const { data, error } = await supabase.from("workspace_members").select("workspace_id, role, workspaces(id, name)").eq("user_id", ctx.getUserId()).limit(50);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return ok(JSON.stringify(data ?? []), { workspaces: data ?? [] });
    }
  )
});

// src/lib/mcp/index.ts
var projectRef = "stuaikfyuwcjmchcvfie";
var mcp_default = defineMcp({
  name: "nexusflo24-mcp",
  title: "NexusFlo24 MCP",
  version: "0.1.0",
  instructions: "Tools for NexusFlo24 \u2014 an AI-powered marketing automation platform. Use `list_workspaces` first to find the caller's workspace_id, then `list_leads`, `create_lead`, and `list_campaigns` to work with their CRM and campaigns.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_workspaces_default, list_leads_default, create_lead_default, list_campaigns_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
